version: '3.9'
services:
    ghproxy:
        image: 'wjqserver/ghproxy:latest'
        restart: always
        volumes:
            - './ghproxy/log/run:/data/ghproxy/log'
            - './ghproxy/log/caddy:/data/caddy/log'
            - './ghproxy/config:/data/ghproxy/config'
            - './data/www:/data/www'
        ports:
          - '127.0.0.1:5000:8080'
